version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=arh
      - DB_PORT=3306
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arh
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
